# Generated by Django 4.1.3 on 2022-11-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptionplan_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='period',
            field=models.IntegerField(choices=[(0, 'Yearly'), (1, 'Monthly')]),
        ),
    ]
