# Generated by Django 4.1.3 on 2022-12-05 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0009_subscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.paymentmethod'),
        ),
    ]
