# Generated by Django 4.1.2 on 2022-11-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userenroll',
            name='user',
        ),
    ]
