# Generated by Django 4.1.3 on 2022-11-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_userenroll_user_alter_timeinterval_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinstance',
            name='class_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classoffering'),
        ),
    ]
