# Generated by Django 4.1.3 on 2022-11-18 16:08

import classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_remove_userenroll_timeslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoffering',
            name='end_recursion_date',
            field=models.DateField(validators=[classes.models.end_recursion_only_gte_today]),
        ),
    ]
