# Generated by Django 4.1.3 on 2022-12-04 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_rename_userenroll_userinstanceenroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoffering',
            name='start_recursion_date',
            field=models.DateField(default=datetime.date(2022, 12, 4)),
            preserve_default=False,
        ),
    ]
