# Generated by Django 4.1.3 on 2022-11-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tfcuser_password_alter_tfcuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfcuser',
            name='avatar',
            field=models.ImageField(upload_to='user-images'),
        ),
    ]
