# Generated by Django 4.1.3 on 2022-11-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
