# Generated by Django 4.1.3 on 2022-12-09 06:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0011_remove_subscription_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='expiration',
            field=models.DateField(default=datetime.date(2022, 12, 9)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(default='Kenneth', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to=settings.AUTH_USER_MODEL),
        ),
    ]
