# Generated by Django 4.1.3 on 2022-11-15 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('classes', '0003_alter_timeinterval_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classoffering',
            name='times',
        ),
    ]
