# Generated by Django 4.1.3 on 2022-11-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_classinstance_class_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenroll',
            name='timeslot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.timeinterval'),
            preserve_default=False,
        ),
    ]
